#!/usr/bin/python3
from octoniones import *

a = input("Introducir real z1: ")
b = input("Introducir imaginario z1: ")
c = input("Introducir real z2: ")
d = input("Introducir imaginario z2: ")
f = input("Introducir real z3: ")
g = input("Introducir imaginario z3: ")
print()
z1 = Complejos(a,b)
z2 = Complejos(c,d)
z3 = Complejos(f,g)

C1 = Cuaterniones(z1, z2)
C2 = Cuaterniones(z2, z3)
C3 = Cuaterniones(z1, z3)

O1 = Octoniones(C1, C2)
O2 = Octoniones(C3, C1)
O3 = Octoniones(C2, C3)

print ("Primer Octanion O1=(C1,C2):",O1)
print ("Segundo Octanion O2=(C2,C3):",O2)
print ("Tercer Octanion O3=(C1,C3):",O3)
print ("Suma de O1 + O2:",O1+O2)
print ("Suma de O2 + O3:",O2+O3)
print ("Suma de O1 + O3:",O1+O3)
print ("Resta de O1 - O2:",O1-O2)
print ("Resta de O2 - O3:",O2-O3)
print ("Resta de O1 - O3:",O1-O3)
print ("Aqui demostraremos que los octoniones tampoco son conmutables")
print ("Multiplicacion de O1*O2",O1*O2)
print ("Multiplicacion de O2*O1",O2*O1)
print ("Como pudimos notar los resultados son distintos, con distintos componentes")
print ("Modulo de O1:",O1.__pow__())
print ("Modulo de O2:",O2.__pow__())
print ("Modulo de O3:",O3.__pow__())
print()